//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema_WFA.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name productId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        Tema_WFA.ServiceReference1.AddProductResponse AddProduct(Tema_WFA.ServiceReference1.AddProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.AddProductResponse> AddProductAsync(Tema_WFA.ServiceReference1.AddProductRequest request);
        
        // CODEGEN: Generating message contract since element name productId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        Tema_WFA.ServiceReference1.UpdateProductResponse UpdateProduct(Tema_WFA.ServiceReference1.UpdateProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.UpdateProductResponse> UpdateProductAsync(Tema_WFA.ServiceReference1.UpdateProductRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductIdsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductIds", ReplyAction="*")]
        Tema_WFA.ServiceReference1.GetProductIdsResponse GetProductIds(Tema_WFA.ServiceReference1.GetProductIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductIds", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.GetProductIdsResponse> GetProductIdsAsync(Tema_WFA.ServiceReference1.GetProductIdsRequest request);
        
        // CODEGEN: Generating message contract since element name productID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        Tema_WFA.ServiceReference1.DeleteProductResponse DeleteProduct(Tema_WFA.ServiceReference1.DeleteProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.DeleteProductResponse> DeleteProductAsync(Tema_WFA.ServiceReference1.DeleteProductRequest request);
        
        // CODEGEN: Generating message contract since element name productID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductInfo", ReplyAction="*")]
        Tema_WFA.ServiceReference1.GetProductInfoResponse GetProductInfo(Tema_WFA.ServiceReference1.GetProductInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.GetProductInfoResponse> GetProductInfoAsync(Tema_WFA.ServiceReference1.GetProductInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProduct", Namespace="http://tempuri.org/", Order=0)]
        public Tema_WFA.ServiceReference1.AddProductRequestBody Body;
        
        public AddProductRequest() {
        }
        
        public AddProductRequest(Tema_WFA.ServiceReference1.AddProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string quantity;
        
        public AddProductRequestBody() {
        }
        
        public AddProductRequestBody(string productId, string name, string price, string quantity) {
            this.productId = productId;
            this.name = name;
            this.price = price;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema_WFA.ServiceReference1.AddProductResponseBody Body;
        
        public AddProductResponse() {
        }
        
        public AddProductResponse(Tema_WFA.ServiceReference1.AddProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddProductResponseBody {
        
        public AddProductResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProduct", Namespace="http://tempuri.org/", Order=0)]
        public Tema_WFA.ServiceReference1.UpdateProductRequestBody Body;
        
        public UpdateProductRequest() {
        }
        
        public UpdateProductRequest(Tema_WFA.ServiceReference1.UpdateProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string quantity;
        
        public UpdateProductRequestBody() {
        }
        
        public UpdateProductRequestBody(string productId, string name, string price, string quantity) {
            this.productId = productId;
            this.name = name;
            this.price = price;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema_WFA.ServiceReference1.UpdateProductResponseBody Body;
        
        public UpdateProductResponse() {
        }
        
        public UpdateProductResponse(Tema_WFA.ServiceReference1.UpdateProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateProductResponseBody {
        
        public UpdateProductResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductIdsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductIds", Namespace="http://tempuri.org/", Order=0)]
        public Tema_WFA.ServiceReference1.GetProductIdsRequestBody Body;
        
        public GetProductIdsRequest() {
        }
        
        public GetProductIdsRequest(Tema_WFA.ServiceReference1.GetProductIdsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductIdsRequestBody {
        
        public GetProductIdsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductIdsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema_WFA.ServiceReference1.GetProductIdsResponseBody Body;
        
        public GetProductIdsResponse() {
        }
        
        public GetProductIdsResponse(Tema_WFA.ServiceReference1.GetProductIdsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductIdsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema_WFA.ServiceReference1.ArrayOfString GetProductIdsResult;
        
        public GetProductIdsResponseBody() {
        }
        
        public GetProductIdsResponseBody(Tema_WFA.ServiceReference1.ArrayOfString GetProductIdsResult) {
            this.GetProductIdsResult = GetProductIdsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProduct", Namespace="http://tempuri.org/", Order=0)]
        public Tema_WFA.ServiceReference1.DeleteProductRequestBody Body;
        
        public DeleteProductRequest() {
        }
        
        public DeleteProductRequest(Tema_WFA.ServiceReference1.DeleteProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productID;
        
        public DeleteProductRequestBody() {
        }
        
        public DeleteProductRequestBody(string productID) {
            this.productID = productID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema_WFA.ServiceReference1.DeleteProductResponseBody Body;
        
        public DeleteProductResponse() {
        }
        
        public DeleteProductResponse(Tema_WFA.ServiceReference1.DeleteProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteProductResult;
        
        public DeleteProductResponseBody() {
        }
        
        public DeleteProductResponseBody(string DeleteProductResult) {
            this.DeleteProductResult = DeleteProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductInfo", Namespace="http://tempuri.org/", Order=0)]
        public Tema_WFA.ServiceReference1.GetProductInfoRequestBody Body;
        
        public GetProductInfoRequest() {
        }
        
        public GetProductInfoRequest(Tema_WFA.ServiceReference1.GetProductInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productID;
        
        public GetProductInfoRequestBody() {
        }
        
        public GetProductInfoRequestBody(string productID) {
            this.productID = productID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tema_WFA.ServiceReference1.GetProductInfoResponseBody Body;
        
        public GetProductInfoResponse() {
        }
        
        public GetProductInfoResponse(Tema_WFA.ServiceReference1.GetProductInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Tema_WFA.ServiceReference1.ArrayOfString GetProductInfoResult;
        
        public GetProductInfoResponseBody() {
        }
        
        public GetProductInfoResponseBody(Tema_WFA.ServiceReference1.ArrayOfString GetProductInfoResult) {
            this.GetProductInfoResult = GetProductInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Tema_WFA.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Tema_WFA.ServiceReference1.WebService1Soap>, Tema_WFA.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema_WFA.ServiceReference1.AddProductResponse Tema_WFA.ServiceReference1.WebService1Soap.AddProduct(Tema_WFA.ServiceReference1.AddProductRequest request) {
            return base.Channel.AddProduct(request);
        }
        
        public void AddProduct(string productId, string name, string price, string quantity) {
            Tema_WFA.ServiceReference1.AddProductRequest inValue = new Tema_WFA.ServiceReference1.AddProductRequest();
            inValue.Body = new Tema_WFA.ServiceReference1.AddProductRequestBody();
            inValue.Body.productId = productId;
            inValue.Body.name = name;
            inValue.Body.price = price;
            inValue.Body.quantity = quantity;
            Tema_WFA.ServiceReference1.AddProductResponse retVal = ((Tema_WFA.ServiceReference1.WebService1Soap)(this)).AddProduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.AddProductResponse> Tema_WFA.ServiceReference1.WebService1Soap.AddProductAsync(Tema_WFA.ServiceReference1.AddProductRequest request) {
            return base.Channel.AddProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.AddProductResponse> AddProductAsync(string productId, string name, string price, string quantity) {
            Tema_WFA.ServiceReference1.AddProductRequest inValue = new Tema_WFA.ServiceReference1.AddProductRequest();
            inValue.Body = new Tema_WFA.ServiceReference1.AddProductRequestBody();
            inValue.Body.productId = productId;
            inValue.Body.name = name;
            inValue.Body.price = price;
            inValue.Body.quantity = quantity;
            return ((Tema_WFA.ServiceReference1.WebService1Soap)(this)).AddProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema_WFA.ServiceReference1.UpdateProductResponse Tema_WFA.ServiceReference1.WebService1Soap.UpdateProduct(Tema_WFA.ServiceReference1.UpdateProductRequest request) {
            return base.Channel.UpdateProduct(request);
        }
        
        public void UpdateProduct(string productId, string name, string price, string quantity) {
            Tema_WFA.ServiceReference1.UpdateProductRequest inValue = new Tema_WFA.ServiceReference1.UpdateProductRequest();
            inValue.Body = new Tema_WFA.ServiceReference1.UpdateProductRequestBody();
            inValue.Body.productId = productId;
            inValue.Body.name = name;
            inValue.Body.price = price;
            inValue.Body.quantity = quantity;
            Tema_WFA.ServiceReference1.UpdateProductResponse retVal = ((Tema_WFA.ServiceReference1.WebService1Soap)(this)).UpdateProduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.UpdateProductResponse> Tema_WFA.ServiceReference1.WebService1Soap.UpdateProductAsync(Tema_WFA.ServiceReference1.UpdateProductRequest request) {
            return base.Channel.UpdateProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.UpdateProductResponse> UpdateProductAsync(string productId, string name, string price, string quantity) {
            Tema_WFA.ServiceReference1.UpdateProductRequest inValue = new Tema_WFA.ServiceReference1.UpdateProductRequest();
            inValue.Body = new Tema_WFA.ServiceReference1.UpdateProductRequestBody();
            inValue.Body.productId = productId;
            inValue.Body.name = name;
            inValue.Body.price = price;
            inValue.Body.quantity = quantity;
            return ((Tema_WFA.ServiceReference1.WebService1Soap)(this)).UpdateProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema_WFA.ServiceReference1.GetProductIdsResponse Tema_WFA.ServiceReference1.WebService1Soap.GetProductIds(Tema_WFA.ServiceReference1.GetProductIdsRequest request) {
            return base.Channel.GetProductIds(request);
        }
        
        public Tema_WFA.ServiceReference1.ArrayOfString GetProductIds() {
            Tema_WFA.ServiceReference1.GetProductIdsRequest inValue = new Tema_WFA.ServiceReference1.GetProductIdsRequest();
            inValue.Body = new Tema_WFA.ServiceReference1.GetProductIdsRequestBody();
            Tema_WFA.ServiceReference1.GetProductIdsResponse retVal = ((Tema_WFA.ServiceReference1.WebService1Soap)(this)).GetProductIds(inValue);
            return retVal.Body.GetProductIdsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.GetProductIdsResponse> Tema_WFA.ServiceReference1.WebService1Soap.GetProductIdsAsync(Tema_WFA.ServiceReference1.GetProductIdsRequest request) {
            return base.Channel.GetProductIdsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.GetProductIdsResponse> GetProductIdsAsync() {
            Tema_WFA.ServiceReference1.GetProductIdsRequest inValue = new Tema_WFA.ServiceReference1.GetProductIdsRequest();
            inValue.Body = new Tema_WFA.ServiceReference1.GetProductIdsRequestBody();
            return ((Tema_WFA.ServiceReference1.WebService1Soap)(this)).GetProductIdsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema_WFA.ServiceReference1.DeleteProductResponse Tema_WFA.ServiceReference1.WebService1Soap.DeleteProduct(Tema_WFA.ServiceReference1.DeleteProductRequest request) {
            return base.Channel.DeleteProduct(request);
        }
        
        public string DeleteProduct(string productID) {
            Tema_WFA.ServiceReference1.DeleteProductRequest inValue = new Tema_WFA.ServiceReference1.DeleteProductRequest();
            inValue.Body = new Tema_WFA.ServiceReference1.DeleteProductRequestBody();
            inValue.Body.productID = productID;
            Tema_WFA.ServiceReference1.DeleteProductResponse retVal = ((Tema_WFA.ServiceReference1.WebService1Soap)(this)).DeleteProduct(inValue);
            return retVal.Body.DeleteProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.DeleteProductResponse> Tema_WFA.ServiceReference1.WebService1Soap.DeleteProductAsync(Tema_WFA.ServiceReference1.DeleteProductRequest request) {
            return base.Channel.DeleteProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.DeleteProductResponse> DeleteProductAsync(string productID) {
            Tema_WFA.ServiceReference1.DeleteProductRequest inValue = new Tema_WFA.ServiceReference1.DeleteProductRequest();
            inValue.Body = new Tema_WFA.ServiceReference1.DeleteProductRequestBody();
            inValue.Body.productID = productID;
            return ((Tema_WFA.ServiceReference1.WebService1Soap)(this)).DeleteProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tema_WFA.ServiceReference1.GetProductInfoResponse Tema_WFA.ServiceReference1.WebService1Soap.GetProductInfo(Tema_WFA.ServiceReference1.GetProductInfoRequest request) {
            return base.Channel.GetProductInfo(request);
        }
        
        public Tema_WFA.ServiceReference1.ArrayOfString GetProductInfo(string productID) {
            Tema_WFA.ServiceReference1.GetProductInfoRequest inValue = new Tema_WFA.ServiceReference1.GetProductInfoRequest();
            inValue.Body = new Tema_WFA.ServiceReference1.GetProductInfoRequestBody();
            inValue.Body.productID = productID;
            Tema_WFA.ServiceReference1.GetProductInfoResponse retVal = ((Tema_WFA.ServiceReference1.WebService1Soap)(this)).GetProductInfo(inValue);
            return retVal.Body.GetProductInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.GetProductInfoResponse> Tema_WFA.ServiceReference1.WebService1Soap.GetProductInfoAsync(Tema_WFA.ServiceReference1.GetProductInfoRequest request) {
            return base.Channel.GetProductInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Tema_WFA.ServiceReference1.GetProductInfoResponse> GetProductInfoAsync(string productID) {
            Tema_WFA.ServiceReference1.GetProductInfoRequest inValue = new Tema_WFA.ServiceReference1.GetProductInfoRequest();
            inValue.Body = new Tema_WFA.ServiceReference1.GetProductInfoRequestBody();
            inValue.Body.productID = productID;
            return ((Tema_WFA.ServiceReference1.WebService1Soap)(this)).GetProductInfoAsync(inValue);
        }
    }
}
