//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.Users = new HashSet<User>();
        }
    
        public string CartID { get; set; }
        public string OrderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
