//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Carts = new HashSet<Cart>();
        }
    
        public string OrderID { get; set; }
        public string ID { get; set; }
        public string ProductID { get; set; }
        public string Qty { get; set; }
        public string Price { get; set; }
        public string Status { get; set; }
        public string TotalPrice { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Product Product { get; set; }
    }
}
